# Generated by Django 2.2.24 on 2021-06-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='gender',
            field=models.CharField(choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=1),
        ),
    ]
