# Generated by Django 2.2.24 on 2021-06-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_submission_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
