# Generated by Django 2.2.24 on 2021-06-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_auto_20210613_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='age',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
